name: Run Ubuntu System Tests

on:
  workflow_call:
  workflow_dispatch:

jobs:
  run-tests:
    name: Run Tests
    runs-on:
    - self-hosted
    - linux
    - x64
    - grpcbot-ubuntu2

    steps:
    - name: Download Tests Artifact
      uses: actions/download-artifact@v4
      with:
        name: ni-grpc-device-tests-linux-glibc2_38-x64

    - run: ls -R

    - name: Untar Test Build Files
      run: >-
        tar -xvzf ni-grpc-device-tests-linux-glibc2_38-x64.tar.gz

    - name: Run System Tests
      run: ./SystemTestsRunner --gtest_filter=-NiRFSA*:NiRFSG*:NiDCPower*CalSelfCalibrate*:NiXnetLINDriverApiTests.ConvertFramesToFromSignalsFromExample_CompareFrames_ValuesMatch
      timeout-minutes: 27
